steps:
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['install']
#  dir: 'function/dir/from/repo/root'
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['test']
#  dir: 'function/dir/from/repo/root'

#gcloud functions deploy helloGET --runtime nodejs10 --trigger-http --allow-unauthenticated
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'paytify', '--trigger-http', '--runtime', 'nodejs10', '--allow-unauthenticated']
  dir: 'src/functions/ptyGateway'