steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'src/functions/ptyGateway'
  
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'src/functions/ptyGateway'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'paytify', '--trigger-http', '--runtime', 'nodejs10', '--allow-unauthenticated']
  dir: 'src/functions/ptyGateway'
  
#gcloud functions deploy paytify --runtime nodejs10 --trigger-http --allow-unauthenticated